const videoProjects=[
{title:'Levia Property 01',category:'Advertise',year:'2026',thumbnail:'images/video/levia-property-1.png',videoUrl:'https://drive.google.com/file/d/1SSkhwrpwnWUK-GE4GAra1ArMFREFm-gh/view?usp=share_link',description:'An advertising video for Levia Property.'},
{title:'Levia Property 02',category:'Advertise',year:'2026',thumbnail:'images/video/levia-property-2.png',videoUrl:'https://drive.google.com/file/d/1ph0udAiDmv3BlV5Vlkvctx7rB9YoP5-t/view?usp=share_link',description:'An advertising video for Levia Property.'},
{title:'Levia Property 03',category:'Advertise',year:'2026',thumbnail:'images/video/levia-property-3.png',videoUrl:'https://drive.google.com/file/d/1oo87gxkOPrW62kfoiTRAxtCnvP1tdKE-/view?usp=share_link',description:'An advertising video for Levia Property.'},
{title:'Levia Property 04',category:'Advertise',year:'2026',thumbnail:'images/video/levia-property-4.png',videoUrl:'https://drive.google.com/file/d/1mHqZwG9XoVINqdpd_sZX5ftP-xVmEASa/view?usp=share_link',description:'An advertising video for Levia Property.'},
{title:'Impact Mint',category:'Advertise',year:'2026',thumbnail:'images/video/impact-mint.png',videoUrl:'https://drive.google.com/file/d/15FlG2gPqyUkRXJy-d0jzcCce9NIDvtqr/view?usp=share_link',description:'A product video for Impact Mints with a bright, playful visual style.'},
{title:'延爱',category:'Advertise',year:'2024',thumbnail:'images/video/yan-ai.png',videoUrl:'https://drive.google.com/file/d/1eXjDPLSk2QH6fhgc7HRZ6l__5HRlIflc/view?usp=share_link',description:'A video with a soft, emotional visual tone.'},
{title:'My Dark History S2 EP1',category:'Show',year:'2026',thumbnail:'images/video/my-dark-history-s2-ep1.jpg',videoUrl:'https://youtu.be/Gzboc-GsAXA',description:'A YouTube show episode for My Dark History Season 2.'},
{title:'活动－爱心手拉手',category:'Event',year:'2025',thumbnail:'https://drive.google.com/thumbnail?id=1kMigpyv9gqYWhvMB-T8KEkinZCI5umCW&sz=w1200',videoUrl:'https://drive.google.com/file/d/1kMigpyv9gqYWhvMB-T8KEkinZCI5umCW/view?usp=share_link',description:'An event highlight film celebrating connection, generosity and community.'},
{title:'是不是 不爱我了',category:'MV',year:'2025',thumbnail:'images/video/bu-shi-bu-ai-wo-le.png',videoUrl:'https://youtu.be/hiDgtJdaXnc?si=xyG-KSremer2TIQR',description:'A tender music video about the quiet uncertainty between two people.'},
{title:'Rasa / Every day',category:'Corporate',year:'2024',thumbnail:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80',videoUrl:'',description:'Small rituals, made cinematic.'}
];
document.querySelector('.hero h1').innerHTML='A few free spirits<br><em>bring the images in your mind to life.</em>';document.querySelector('.hero .text-link').href='play.html';document.head.insertAdjacentHTML('beforeend','<style>.album-grid{columns:1!important;max-width:1050px;margin:0 auto}.album-grid img{margin-bottom:22px!important;aspect-ratio:auto;object-fit:contain}</style>');
const projects=[
['Atlas / New Balance','Commercial · 2025','https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=1200&q=80'],['是不是 不爱我了','MV · 2025','images/video/bu-shi-bu-ai-wo-le.png','https://youtu.be/hiDgtJdaXnc?si=xyG-KSremer2TIQR'],['Rasa / Every day','Brand film · 2024','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80'],['We are here','Portrait series · 2024','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=80']];
projects[0]=['活动－爱心手拉手','Event Highlight','https://drive.google.com/thumbnail?id=1kMigpyv9gqYWhvMB-T8KEkinZCI5umCW&sz=w1200','https://drive.google.com/file/d/1kMigpyv9gqYWhvMB-T8KEkinZCI5umCW/view?usp=share_link'];document.querySelector('#workGrid').innerHTML=projects.slice(1).map(p=>{const tag=p[3]?'a':'article',attrs=p[3]?`href="${p[3]}" target="_blank" rel="noopener" style="text-decoration:none;color:inherit"`:'';return `<${tag} class="project" ${attrs}><img loading="lazy" src="${p[2]}" alt="${p[0]}"><div><h3>${p[0]}</h3><small>${p[1].replace(/ · \d{4}/g,'')}</small></div></${tag}>`}).join('');
const featuredVideoIndex=7;document.querySelector('#workGrid').insertAdjacentHTML('afterbegin',`<article class="project featured-video" data-video="${featuredVideoIndex}"><img loading="lazy" src="${videoProjects[featuredVideoIndex].thumbnail}" alt="${videoProjects[featuredVideoIndex].title}"><div><h3>${videoProjects[featuredVideoIndex].title}</h3><small>${videoProjects[featuredVideoIndex].category} · Watch film ↗</small></div></article>`);
const videoDialog=document.querySelector('#videoDialog');document.querySelector('#workGrid').addEventListener('click',e=>{const card=e.target.closest('[data-video]');if(!card)return;const v=videoProjects[card.dataset.video];if(!v.videoUrl)return;if(!v.videoUrl.includes('youtu')){window.open(v.videoUrl,'_blank','noopener');return}const id=new URL(v.videoUrl).pathname.split('/').pop();document.querySelector('#videoTitle').textContent=v.title;document.querySelector('#videoMeta').textContent=v.category;document.querySelector('#videoDescription').textContent=v.description;document.querySelector('#youtubeLink').href=v.videoUrl;document.querySelector('#videoPlayer').src=`https://www.youtube.com/embed/${id}?autoplay=1`;videoDialog.showModal()});videoDialog.querySelector('.close').onclick=()=>{document.querySelector('#videoPlayer').src='';videoDialog.close()};
const kit=[];
const grid=document.querySelector('#rentalGrid'),dialog=document.querySelector('#rentalDialog');function renderKit(){document.querySelector('#rentalFilters').innerHTML='';grid.innerHTML='<article class="rental-empty"><h3>Not available yet</h3></article>'};renderKit();
document.querySelector('#rentalFilters').onclick=e=>{};
let selected;grid.onclick=e=>{};function updateTotal(){return}document.querySelector('#rentalDays').oninput=updateTotal;document.querySelector('#rentalDate').onchange=updateTotal;document.querySelector('.close').onclick=()=>dialog.close();
document.querySelector('.enquiry form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,name=form.querySelector('input[placeholder="Name"]').value||'Not provided',email=form.querySelector('input[type="email"]').value||'Not provided',service=form.querySelector('select').value,msg=`Hi Zeal Production,%0A%0AI would like to start a project.%0A%0AName: ${encodeURIComponent(name)}%0AEmail: ${encodeURIComponent(email)}%0AService: ${encodeURIComponent(service)}%0A%0APlease get back to me. Thank you.`;window.open('https://wa.me/60197512803?text='+msg,'_blank','noopener')});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.intro,.project,.photo-copy,.edit-copy,.services article,.rental-item,.about>div:last-child').forEach(el=>observer.observe(el));

const photoProjects=[
{title:'Flower',category:'Style',year:'2026',image:'images/flower/5.jpg',description:'A soft garden portrait series with floral details and natural light.'},
{title:'Art',category:'Style',year:'2026',image:'images/art/IMG_9693.JPG',description:'A styled art portrait series with dramatic colour, texture and movement.'},
{title:'Solo',category:'Style',year:'2026',image:'images/solo/IMG_8011.JPG',description:'A styled solo portrait session with a clean, natural mood.'},
{title:'Halloween Annual Dinner',category:'Event Photography',year:'2024',image:'images/halloween-annual-dinner/17-10-2024_Halloween Event0118.jpg',description:'Event photography coverage for a Halloween annual dinner.'},
{title:'Dking X Medical',category:'Event Photography',year:'2026',image:'images/dking-x-medical/DurianCulturalFest2024(16thSept)_0001.jpg',description:'Event photography coverage for Dking X Medical.'},
{title:'Graduation',category:'Graduation Photography',year:'2026',image:'images/graduation/DSC05587.jpg',description:'A graduation portrait session celebrating a bright new chapter.'},
{title:'Unlock Dance Studio',category:'Event Photography',year:'2026',image:'images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0025.jpg',description:'A vibrant grand opening celebration for Unlock Dance Studio.'},
{title:'Aistru Grand Opening',category:'Event Photography',year:'2025',image:'images/aistru-grand-opening/Aistru_23-11-20250005.jpg',description:'A lively brand celebration captured in candid, colourful moments.'},
{title:'MCD CNY SONG – Money好势料',category:'BTS',year:'2026',image:'images/mcd-cny-song/CNY%20BTS_23-11-20250211.jpg',description:'Behind-the-scenes moments from a vibrant Chinese New Year music production.'},
{title:'Baby Birthday-Alperen',category:'Event Photography',year:'2025',image:'images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0094.jpg',description:'A joyful birthday celebration for Alperen, filled with family, friends and playful moments.'},
{title:'Baby Birthday-Jayhinz & Joyous',category:'Event Photography',year:'2025',image:'images/baby-birthday-jayhinz-joyous/0019.jpg',description:'A bright and joyful birthday celebration for Jayhinz and Joyous.'}
];
const photoAlbums={
'Flower':['images/flower/5.jpg','images/flower/2.jpg','images/flower/1.jpg','images/flower/4.jpg','images/flower/3.jpg','images/flower/6.jpg'],
'Art':['images/art/IMG_9693.JPG','images/art/IMG_9707.JPG','images/art/IMG_9699.JPG','images/art/IMG_9691.JPG','images/art/IMG_9689.JPG','images/art/IMG_9696.JPG','images/art/IMG_9686.JPG'],
'Solo':['images/solo/IMG_8011.JPG','images/solo/IMG_8012.JPG','images/solo/IMG_8009.JPG','images/solo/IMG_8014.JPG','images/solo/IMG_8013.JPG'],
'Halloween Annual Dinner':['images/halloween-annual-dinner/17-10-2024_Halloween Event0118.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0143.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0221.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0277.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0319.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0327.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0372.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0474.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0598.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0641.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0736.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event0867.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event1107.jpg','images/halloween-annual-dinner/17-10-2024_Halloween Event1308.jpg'],
'Dking X Medical':['images/dking-x-medical/DurianCulturalFest2024(16thSept)_0001.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0006.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0007.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0010.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0014.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0020.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0025.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0065.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0068.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0069.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0073.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0074.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0085.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0087.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0103.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0124.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0131.jpg','images/dking-x-medical/DurianCulturalFest2024(16thSept)_0135.jpg'],
'Graduation':['images/graduation/DSC05546.jpg','images/graduation/DSC05877.jpg','images/graduation/DSC05587.jpg','images/graduation/DSC05801.jpg','images/graduation/DSC05486.jpg','images/graduation/DSC05660.jpg'],
'Unlock Dance Studio':['images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0025.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0184.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0083.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0213.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0002.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0014.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0017.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0021.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0030.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0247.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0264.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0295.jpg','images/unlock-dance-studio/01-03-2026_Unlock%20Dance%20Studio0303.jpg'],
'Aistru Grand Opening':['images/aistru-grand-opening/Aistru_23-11-20250005.jpg','images/aistru-grand-opening/Aistru_23-11-20250007.jpg','images/aistru-grand-opening/Aistru_23-11-20250009.jpg','images/aistru-grand-opening/Aistru_23-11-20250020.jpg','images/aistru-grand-opening/Aistru_23-11-20250024.jpg','images/aistru-grand-opening/Aistru_23-11-20250026.jpg','images/aistru-grand-opening/Aistru_23-11-20250028.jpg','images/aistru-grand-opening/Aistru_23-11-20250031.jpg','images/aistru-grand-opening/Aistru_23-11-20250033.jpg','images/aistru-grand-opening/Aistru_23-11-20250041.jpg','images/aistru-grand-opening/Aistru_23-11-20250044.jpg','images/aistru-grand-opening/Aistru_23-11-20250047.jpg','images/aistru-grand-opening/Aistru_23-11-20250050.jpg','images/aistru-grand-opening/Aistru_23-11-20250057.jpg','images/aistru-grand-opening/Aistru_23-11-20250064.jpg','images/aistru-grand-opening/Aistru_23-11-20250069.jpg','images/aistru-grand-opening/Aistru_23-11-20250083.jpg','images/aistru-grand-opening/Aistru_23-11-20250086.jpg'],
'MCD CNY SONG – Money好势料':['images/mcd-cny-song/CNY%20BTS_23-11-20250014.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250016.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250021.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250027.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250040.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250043.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250058.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250060.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250093.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250116.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250128.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250130.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250131.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250154.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250179.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250197.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250211.jpg','images/mcd-cny-song/CNY%20BTS_23-11-20250223.jpg'],
'Baby Birthday-Alperen':['images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0094.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0010.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0001.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0013.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0027.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0033.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0057.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0038.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0039.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0069.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0072.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0079.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0093.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0113.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0123.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0135.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0019.jpg','images/baby-birthday-alperen/Copy%20of%2019-1-2025_Birthday%20Party0070.jpg'],
'Baby Birthday-Jayhinz & Joyous':['images/baby-birthday-jayhinz-joyous/0019.jpg','images/baby-birthday-jayhinz-joyous/0163.jpg','images/baby-birthday-jayhinz-joyous/0015.jpg','images/baby-birthday-jayhinz-joyous/0011.jpg','images/baby-birthday-jayhinz-joyous/0024.jpg','images/baby-birthday-jayhinz-joyous/0021.jpg','images/baby-birthday-jayhinz-joyous/0079.jpg','images/baby-birthday-jayhinz-joyous/0114.jpg','images/baby-birthday-jayhinz-joyous/0143.jpg','images/baby-birthday-jayhinz-joyous/0147.jpg','images/baby-birthday-jayhinz-joyous/0153.jpg','images/baby-birthday-jayhinz-joyous/0030.jpg','images/baby-birthday-jayhinz-joyous/0084.jpg','images/baby-birthday-jayhinz-joyous/0087.jpg','images/baby-birthday-jayhinz-joyous/0109.jpg','images/baby-birthday-jayhinz-joyous/0108.jpg','images/baby-birthday-jayhinz-joyous/0118.jpg','images/baby-birthday-jayhinz-joyous/0135.jpg','images/baby-birthday-jayhinz-joyous/0151.jpg','images/baby-birthday-jayhinz-joyous/0129.jpg']
};
const editingProjects=[
{title:'My Dark History S2 EP1',category:'Post-Production',year:'2026',image:'images/video/my-dark-history-s2-ep1.jpg',videoUrl:'https://youtu.be/Gzboc-GsAXA',description:'Post-production work for My Dark History Season 2 Episode 1.'},
{title:'Elaine Wong-Proton S70 Reels',category:'Social Media',year:'2026',image:'images/elaine-wong-proton-s70-reels.png',videoUrl:'https://www.instagram.com/reel/DRBgV4pAY_j/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==',description:'Post-production for Elaine Wong’s Proton S70 reels campaign.'},
{title:'ConNichiwa2025-Promo Reels 1',category:'Social Media',year:'2026',image:'images/connichiwa-promo-reels-1.png',videoUrl:'https://www.instagram.com/reel/DKh8PE9Two3/?igsh=czNmN29uM3p2aTY5',description:'Post-production for a ConNichiwa 2025 social media promo reel.'},
{title:'DRUM X MAQ Limited Collection Video',category:'Social Media',year:'2026',image:'images/drum-x-maq-limited-collection.png',videoUrl:'https://www.instagram.com/reel/DSt37yGiXgE/?igsh=MWdmOWZoMXFwMm94',description:'Post-production for the DRUM X MAQ Limited Collection social media video.'},
{title:"MaqLai - 'SAGA傻瓜'",category:'MV · Edit',year:'2024',image:'images/maqlai-saga.png',videoUrl:'https://www.youtube.com/watch?si=ehAoFPt1fbCjDX9f&v=gr62gLXZbbQ&feature=youtu.be',description:'Editing work for MaqLai’s 2024 music video.'},
{title:'My Dark History Season 1-EP3',category:'Post-Production',year:'2025',image:'images/my-dark-history.png',videoUrl:'https://youtu.be/QXjjPppbLoU?si=50yfRuaD1OZYstY_',description:'Post-production work for a 2025 YouTube Show.'},
{title:'My Dark History Season 1-EP1',category:'Post-Production',year:'2025',image:'images/my-dark-history-ep1.png',videoUrl:'https://youtu.be/Dpde86eCyxw?si=j0zTv0yf6Eec2ZFD',description:'Post-production work for a 2025 YouTube Show.'}
];
const colourProjects=[
{title:'隔壁的阿嬷',category:'Colour Grading',year:'2026',image:'images/colour-ge-bi-de-a-ma.png',videoUrl:'https://youtu.be/Dar1XvQFwQ8?si=DfKJhp-m7gwjsrlT',description:'Colour grading work for the short film 隔壁的阿嬷.'}
];
const portfolioSets={video:videoProjects,photo:photoProjects,edit:editingProjects,colour:colourProjects};document.querySelector('.portfolio-tabs').insertAdjacentHTML('beforeend','<button data-portfolio="colour">Colour</button>');let activePortfolio='video',activeCategory='All';const archiveGrid=document.querySelector('#archiveGrid'),archiveFilters=document.querySelector('#portfolioFilters'),portfolioKicker=document.querySelector('#portfolioKicker');
function renderArchive(){const card=(x,i,type)=>`<article class="archive-card ${type}-card" data-portfolio="${type}" data-archive="${i}" style="--float-delay:${i%8}"><img loading="lazy" src="${x.thumbnail||x.image}" alt="${x.title}"><div><h3>${x.title}</h3><p>${x.category}</p><span class="archive-desc">${x.description}</span>${(type==='video'||type==='edit'||type==='colour')&&x.videoUrl?'<a class="watch" href="'+x.videoUrl+'" target="_blank" rel="noopener">Watch video ↗</a>':''}</div></article>`;archiveGrid.classList.remove('archive-grid-all');archiveGrid.classList.toggle('archive-grid-motion',activeCategory==='All');archiveGrid.classList.toggle('archive-grid-video-all',activePortfolio==='video'&&activeCategory==='All');const set=portfolioSets[activePortfolio],categories=['All',...new Set(set.map(x=>x.category))];portfolioKicker.textContent=`${activePortfolio.toUpperCase()} PORTFOLIO`;archiveFilters.innerHTML=categories.map(x=>`<button class="${x===activeCategory?'active':''}" data-category="${x}">${x}</button>`).join('');archiveGrid.innerHTML=set.filter(x=>activeCategory==='All'||x.category===activeCategory).map((x,i)=>card(x,i,activePortfolio)).join('')}
renderArchive();document.querySelector('.portfolio-tabs').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;activePortfolio=e.target.dataset.portfolio;activeCategory='All';document.querySelectorAll('.portfolio-tabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderArchive()});archiveFilters.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;activeCategory=e.target.dataset.category;renderArchive()});document.addEventListener('click',e=>{const link=e.target.closest('[data-portfolio-jump]');if(!link)return;const target=link.dataset.portfolioJump;if(!portfolioSets[target])return;activePortfolio=target;activeCategory='All';document.querySelectorAll('.portfolio-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.portfolio===target));renderArchive();setTimeout(()=>document.querySelector('#portfolio-library')?.scrollIntoView({block:'center'}),0)});
document.body.insertAdjacentHTML('beforeend','<dialog class="album-dialog" id="albumDialog"><button class="close" aria-label="Close">×</button><div class="album-heading"><p class="eyebrow" id="albumMeta"></p><h3 id="albumTitle"></h3></div><div class="album-grid" id="albumGrid"></div></dialog>');document.head.insertAdjacentHTML('beforeend','<style>.archive-card.photo-card{cursor:zoom-in}.photo-stack img[data-photo-open]{cursor:zoom-in}.album-dialog{width:min(1100px,94vw);max-height:92vh;background:#151513;color:#eeeae1;border:0;padding:28px;overflow:auto}.album-dialog::backdrop{background:#050505dd}.album-dialog .close{position:fixed;right:5vw;top:5vh;z-index:2;color:#fff;background:#1c1c1b;border-radius:50%;width:42px;height:42px}.album-heading{margin:8px 0 28px}.album-heading h3{font-size:clamp(30px,4vw,54px)}.album-grid{columns:2;gap:14px}.album-grid img{width:100%;display:block;margin-bottom:14px;break-inside:avoid;filter:brightness(.9)}@media(max-width:650px){.album-dialog{padding:22px}.album-grid{columns:1}}</style>');const albumDialog=document.querySelector('#albumDialog');function openPhotoAlbum(title){const project=photoProjects.find(item=>item.title===title);if(!project)return;const images=photoAlbums[title]||[project.image];document.querySelector('#albumTitle').textContent=title;document.querySelector('#albumMeta').textContent=`${project.category} · ${images.length} photos`;document.querySelector('#albumGrid').innerHTML=images.map((image,index)=>`<img loading="lazy" src="${image}" alt="${title} photo ${index+1}">`).join('');albumDialog.showModal()}archiveGrid.addEventListener('click',e=>{const card=e.target.closest('.photo-card');if(!card||card.dataset.portfolio!=='photo')return;openPhotoAlbum(card.querySelector('h3').textContent)});document.querySelector('.photo-stack')?.addEventListener('click',e=>{const image=e.target.closest('[data-photo-open]');if(!image)return;openPhotoAlbum(image.dataset.photoOpen)});albumDialog.querySelector('.close').onclick=()=>albumDialog.close();
const portfolioNames={video:'Videography',photo:'Photography',edit:'Post-Production',colour:'Colour Grading'};document.querySelectorAll('.portfolio-tabs button').forEach(button=>{button.textContent=portfolioNames[button.dataset.portfolio];button.addEventListener('click',()=>setTimeout(()=>{portfolioKicker.textContent=`${portfolioNames[button.dataset.portfolio].toUpperCase()} PORTFOLIO`},0))});portfolioKicker.textContent='VIDEOGRAPHY PORTFOLIO';archiveGrid.addEventListener('click',e=>{const card=e.target.closest('.archive-card'),type=card?.dataset.portfolio||activePortfolio;if(!card||!['video','edit','colour'].includes(type))return;const title=card.querySelector('h3').textContent,project=portfolioSets[type].find(item=>item.title===title);if(!project?.videoUrl)return;e.preventDefault();e.stopImmediatePropagation();window.open(project.videoUrl,'_blank','noopener')},true);
document.body.insertAdjacentHTML('beforeend','<dialog class="project-dialog" id="projectDialog"><button class="close" aria-label="Close project">×</button><img id="projectImage" alt=""><div><p class="eyebrow" id="projectMeta"></p><h3 id="projectTitle"></h3><p id="projectCopy"></p></div></dialog>');document.head.insertAdjacentHTML('beforeend','<style>.project-dialog{width:min(760px,92vw);padding:0;border:0;background:#171716;color:#eeeae1}.project-dialog::backdrop{background:#050505dd}.project-dialog .close{position:absolute;right:12px;top:10px;z-index:2;color:white;background:#1c1c1b;border-radius:50%;width:40px;height:40px}.project-dialog img{width:100%;height:min(52vh,480px);object-fit:cover;display:block}.project-dialog>div{padding:27px 32px 34px}.project-dialog h3{font-size:33px}.project-dialog p:not(.eyebrow){color:#b5afa4;line-height:1.65;max-width:580px}</style>');const projectDialog=document.querySelector('#projectDialog');archiveGrid.addEventListener('click',e=>{const card=e.target.closest('.archive-card'),type=card?.dataset.portfolio||activePortfolio;if(type==='photo'||e.target.closest('a'))return;if(!card)return;const title=card.querySelector('h3').textContent,project=portfolioSets[type].find(item=>item.title===title);if(!project)return;if(type==='edit'&&project.videoUrl){window.open(project.videoUrl,'_blank','noopener');return}document.querySelector('#projectImage').src=project.thumbnail||project.image;document.querySelector('#projectImage').alt=project.title;document.querySelector('#projectTitle').textContent=project.title;document.querySelector('#projectMeta').textContent=project.category;document.querySelector('#projectCopy').textContent=project.description;projectDialog.showModal()});projectDialog.querySelector('.close').onclick=()=>projectDialog.close();
document.querySelector('#pricing').insertAdjacentHTML('afterend',`<section class="colour-grade" id="colour-grading"><div class="colour-grade-art"></div><div class="colour-grade-copy"><p class="eyebrow">New service / Colour grading</p><h2>Give every frame<br><em>its final feeling.</em></h2><p>Professional colour correction and bespoke cinematic grading for commercials, events, social content and films.</p><div class="grade-details"><span>3–5 working days</span><span>1 revision round</span></div><a class="button gold" href="#portfolio-library" data-portfolio-jump="colour">Enquire for grading ↗</a></div></section>`);document.head.insertAdjacentHTML('beforeend',`<style>.colour-grade{display:grid;grid-template-columns:1fr 1fr;background:#25231f;min-height:560px}.colour-grade-art{background:linear-gradient(135deg,#15171744,#15171711),url('images/edit-suite.png') center/cover}.colour-grade-copy{padding:15% 13%;align-self:center}.colour-grade-copy h2{font-size:clamp(42px,5vw,72px);line-height:1}.colour-grade-copy>p:not(.eyebrow){max-width:420px;color:#b5aea2;line-height:1.75;margin:25px 0}.grade-details{display:flex;gap:20px;flex-wrap:wrap;margin:30px 0;color:var(--gold);font:10px 'DM Mono';text-transform:uppercase}.grade-details span{border-top:1px solid #665a46;padding-top:9px}@media(max-width:760px){.colour-grade{grid-template-columns:1fr}.colour-grade-art{min-height:330px}.colour-grade-copy{padding:80px 7%}}</style>`);const editColourSlider=document.querySelector('.comparison input');if(editColourSlider){const syncEditColour=()=>document.documentElement.style.setProperty('--edit-colour-level',`${editColourSlider.value}%`);syncEditColour();editColourSlider.addEventListener('input',syncEditColour)}

const quotationTabs=document.querySelector('.quotation-tabs'),quotationCards=[...document.querySelectorAll('.quotation-grid article[data-quote-type]')];function setQuotationFilter(type='video'){quotationTabs?.querySelectorAll('[data-quote-filter]').forEach(button=>button.classList.toggle('active',button.dataset.quoteFilter===type));quotationCards.forEach(card=>card.classList.toggle('is-visible',card.dataset.quoteType===type))}if(quotationTabs&&quotationCards.length){quotationTabs.addEventListener('click',event=>{const button=event.target.closest('[data-quote-filter]');if(!button)return;setQuotationFilter(button.dataset.quoteFilter)});setQuotationFilter('video')}
